### ISSUE TITLE
SINTESIS_MARIA JOSE LOPEZ LEYVA

### ISSUE THREAD

**Issue by MariaJose-1007** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-MariaJose-1007#1]
[SINTESIS2_MARIA JOSE LOPEZ LEYVA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-MariaJose-1007/files/12697568/SINTESIS2_MARIA.JOSE.LOPEZ.LEYVA.pdf)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
